import mongoose from 'mongoose';

// ==================== COURSE SCHEMA ====================
const courseSchema = new mongoose.Schema(
  {
    slug: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      lowercase: true,
    },
    title: {
      type: String,
      required: [true, 'Course title is required'],
      trim: true,
    },
    subtitle: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    fullDescription: {
      type: String,
      default: '',
    },
    category: {
      type: String,
      required: true,
      enum: ['foundation', 'ielts', 'elite', 'business', 'online'],
    },
    mode: {
      type: String,
      required: true,
      enum: ['offline', 'online'],
    },
    level: {
      type: String,
      required: true,
    },
    duration: {
      type: String,
      required: true,
    },
    lessons: {
      type: Number,
      default: null,
    },
    students: {
      type: Number,
      default: 0,
    },
    rating: {
      type: Number,
      default: 5.0,
      min: 0,
      max: 5,
    },
    reviewCount: {
      type: Number,
      default: 0,
    },
    price: {
      type: Number,
      required: true,
    },
    salePrice: {
      type: Number,
      default: null,
    },
    currency: {
      type: String,
      default: 'VND',
    },
    thumbnail: {
      type: String,
      default: '',
    },
    instructor: {
      name: { type: String, required: true },
      avatar: { type: String, default: '' },
      title: { type: String, default: '' },
    },
    tags: [{ type: String }],
    highlights: [{ type: String }],
    targetScore: {
      type: String,
      default: null,
    },
    isPopular: {
      type: Boolean,
      default: false,
    },
    isFeatured: {
      type: Boolean,
      default: false,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

// Indexes (chỉ index các field chưa có unique: true)
courseSchema.index({ mode: 1, isActive: 1 });
courseSchema.index({ isFeatured: 1 });
courseSchema.index({ isPopular: 1 });

const Course = mongoose.model('Course', courseSchema);

// ==================== SEED DATA ====================
export const seedCourses = [
  {
    slug: 'ielts-foundation',
    title: 'IELTS Foundation',
    subtitle: 'Nền tảng tiếng Anh cho người mất gốc',
    description: 'Khóa học phù hợp cho người mất gốc hoặc trình độ thấp. Xây dựng nền tảng vững chắc từ cơ bản đến trung cấp.',
    fullDescription: 'Chương trình học được thiết kế đặc biệt cho học viên có nền tảng tiếng Anh yếu. Giáo trình bám sát thực tế, giảng viên tận tâm hỗ trợ 1-1.',
    category: 'foundation',
    mode: 'offline',
    level: 'Beginner',
    duration: '6 tháng',
    lessons: 72,
    students: 1250,
    rating: 4.9,
    reviewCount: 324,
    price: 8500000,
    salePrice: 6800000,
    thumbnail: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=260&fit=crop',
    instructor: { name: 'Ms. Nguyễn Thị Lan', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face', title: 'IELTS 8.5 | 10+ năm giảng dạy' },
    tags: ['IELTS', 'Cơ bản', 'Offline'],
    highlights: ['Lộ trình học cá nhân hóa', 'Giảng viên 1-1', 'Luyện tập thực chiến', 'Đảm bảo đầu ra'],
    targetScore: '5.0 - 6.0',
    isPopular: true,
    isFeatured: false,
  },
  {
    slug: 'ielts-intensive',
    title: 'IELTS Intensive',
    subtitle: 'Luyện thi IELTS cấp tốc 3 tháng',
    description: 'Khóa học cấp tốc cho học viên cần đạt IELTS trong thời gian ngắn. Cam kết 6.5+ trong 3 tháng.',
    fullDescription: 'Chương trình học cường độ cao, tập trung vào các kỹ năng và dạng đề thường gặp trong kỳ thi IELTS thực tế.',
    category: 'ielts',
    mode: 'offline',
    level: 'Intermediate',
    duration: '3 tháng',
    lessons: 48,
    students: 2840,
    rating: 4.8,
    reviewCount: 567,
    price: 12000000,
    salePrice: 9500000,
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=260&fit=crop',
    instructor: { name: 'Mr. Trần Minh Tuấn', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face', title: 'IELTS 9.0 | Band 9 Examiner' },
    tags: ['IELTS', 'Cấp tốc', 'Offline'],
    highlights: ['Cam kết 6.5+', 'Giải đề thật', 'Mock test hàng tuần', 'Feedback chi tiết'],
    targetScore: '6.5 - 7.5',
    isPopular: true,
    isFeatured: true,
  },
  {
    slug: 'ielts-elite',
    title: 'IELTS Elite 1-1',
    subtitle: 'Khóa học cá nhân hóa hoàn toàn',
    description: 'Chương trình học 1-1 với giảng viên IELTS 8.5+. Lộ trình hoàn toàn được cá nhân hóa theo mục tiêu của bạn.',
    fullDescription: 'Trải nghiệm học tập đẳng cấp quốc tế với giảng viên được chứng nhận IELTS 8.5+. Mỗi buổi học được thiết kế riêng cho từng học viên.',
    category: 'elite',
    mode: 'offline',
    level: 'Advanced',
    duration: '2-6 tháng',
    lessons: null,
    students: 450,
    rating: 5.0,
    reviewCount: 128,
    price: 25000000,
    salePrice: null,
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=260&fit=crop',
    instructor: { name: 'Dr. Lê Văn Hùng', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face', title: 'PhD in Education | IELTS 9.0' },
    tags: ['IELTS', '1-1', 'Premium'],
    highlights: ['Học 1-1 hoàn toàn', 'Giảng viên IELTS 9.0', 'Cam kết 7.0+', 'Lịch học linh hoạt'],
    targetScore: '7.0 - 8.5+',
    isPopular: false,
    isFeatured: true,
  },
  {
    slug: 'ielts-online',
    title: 'IELTS Online',
    subtitle: 'Luyện thi IELTS mọi lúc, mọi nơi',
    description: 'Khóa học IELTS Online linh hoạt với nền tảng học tập hiện đại. Học mọi lúc, mọi nơi với chất lượng như offline.',
    fullDescription: 'Hệ thống học online đa tương tác với video bài giảng HD, bài tập thực hành và chữa bài trực tiếp từ giảng viên.',
    category: 'ielts',
    mode: 'online',
    level: 'All levels',
    duration: '4 tháng',
    lessons: 96,
    students: 5200,
    rating: 4.7,
    reviewCount: 892,
    price: 6500000,
    salePrice: 4900000,
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=260&fit=crop',
    instructor: { name: 'Ms. Phạm Thu Hà', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face', title: 'IELTS 8.0 | Online Education Expert' },
    tags: ['IELTS', 'Online', 'Linh hoạt'],
    highlights: ['Học anytime/anywhere', 'Video HD chất lượng cao', 'Tương tác trực tiếp', 'Tài liệu không giới hạn'],
    targetScore: '6.0 - 7.0',
    isPopular: true,
    isFeatured: false,
  },
  {
    slug: 'english-business',
    title: 'Tiếng Anh Doanh nghiệp',
    subtitle: 'Tiếng Anh chuyên nghiệp cho môi trường công sở',
    description: 'Khóa học tiếng Anh thực hành dành cho người đi làm. Tập trung vào email, thuyết trình, đàm phán và giao tiếp công sở.',
    fullDescription: 'Chương trình được thiết kế bởi các chuyên gia với nhiều năm kinh nghiệm trong môi trường doanh nghiệp quốc tế.',
    category: 'business',
    mode: 'offline',
    level: 'Intermediate',
    duration: '4 tháng',
    lessons: 48,
    students: 680,
    rating: 4.9,
    reviewCount: 215,
    price: 9000000,
    salePrice: 7200000,
    thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=260&fit=crop',
    instructor: { name: 'Mr. Nguyễn Đức Anh', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face', title: 'MBA | 15 năm kinh nghiệm quốc tế' },
    tags: ['Business English', 'Offline', 'Chuyên nghiệp'],
    highlights: ['Case study thực tế', 'Role-play doanh nghiệp', 'Giảng viên MBA', 'Chứng chỉ quốc tế'],
    targetScore: null,
    isPopular: false,
    isFeatured: false,
  },
  {
    slug: 'english-foundation-online',
    title: 'Tiếng Anh Mất Gốc Online',
    subtitle: 'Xây dựng nền tảng tiếng Anh từ đầu - Online',
    description: 'Khóa học cho người mất gốc hoàn toàn, học online từ đầu với lộ trình được thiết kế khoa học nhất.',
    fullDescription: 'Từ A đến Z, chúng tôi sẽ xây dựng nền tảng tiếng Anh vững chắc cho bạn thông qua phương pháp học tập hiện đại và hiệu quả.',
    category: 'foundation',
    mode: 'online',
    level: 'Beginner',
    duration: '6 tháng',
    lessons: 120,
    students: 3100,
    rating: 4.8,
    reviewCount: 641,
    price: 5000000,
    salePrice: 3500000,
    thumbnail: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=400&h=260&fit=crop',
    instructor: { name: 'Ms. Võ Thị Mai', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop&crop=face', title: 'TESOL Certified | 8 năm giảng dạy' },
    tags: ['Foundation', 'Online', 'Beginner'],
    highlights: ['Không cần nền tảng', 'Học theo tiến độ cá nhân', 'Giáo trình khoa học', 'Hỗ trợ 24/7'],
    targetScore: null,
    isPopular: true,
    isFeatured: false,
  },
];

export default Course;
